/* Generates the reference docs from world/farm.world.json so the
   prose and the map can never disagree. Run: node tools/build-docs.mjs */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = existsSync(join(root, 'world/active.world.json')) ? 'world/active.world.json' : 'world/farm.world.json';
const W = JSON.parse(readFileSync(join(root, src), 'utf8'));
const byId = (arr) => Object.fromEntries(arr.map((x) => [x.id, x]));
const Z = byId(W.zones), S = byId(W.stations), R = byId(W.roles);
const GEN = '<!-- GENERATED by tools/build-docs.mjs from world/farm.world.json — do not edit by hand. -->';

/* ---------------- roles ---------------- */
let r = `# The roster\n\n${GEN}\n\n`;
const staffed = W.roles.filter((x) => x.agent);
r += `Every role on the farm, grouped by the zone it answers to. **${W.roles.length} roles across ${W.zones.length} zones.**\n\n`;
r += `A role is a charter: what it is for, what it may read, what it may write, and the single place it escalates.\n\n`;
r += `**${staffed.length} of them are live** — they run today as Claude Code subagents in \`.claude/agents/\`, with no\n`;
r += `API key. Invoke one by name, or let the \`farmer\` route to it. The rest are charters waiting for a reason to\n`;
r += `exist; see [08-AGENTS.md](08-AGENTS.md).\n\n`;
if (W.agents) {
  r += `## Live agents\n\n| Agent | Covers | File |\n| --- | --- | --- |\n`;
  for (const [n, a] of Object.entries(W.agents))
    r += `| \`${n}\` | ${a.roles.map((x) => R[x].name).join(', ')} | \`${a.file}\` |\n`;
  r += `\n`;
}
r += `## Model tiers\n\n| Tier | Model | Used for |\n| --- | --- | --- |\n`;
for (const [k, t] of Object.entries(W.modelTiers)) r += `| **${t.label}** | \`${t.model}\` | ${t.use} |\n`;
r += `\n> Tier is a starting recommendation, not a rule. Measure before you move a role down a tier —\n`;
r += `> a cheaper call that needs three retries is not cheaper.\n\n`;
r += `## Index\n\n| Role | Title | Zone | Tier | Live as |\n| --- | --- | --- | --- | --- |\n`;
for (const role of W.roles)
  r += `| [${role.name}](#${role.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}) | ${role.title} | ${Z[role.zone].name} | ${W.modelTiers[role.tier].label} | ${role.agent ? `\`${role.agent}\`` : '—'} |\n`;
r += `\n---\n`;
for (const z of W.zones) {
  const rs = W.roles.filter((x) => x.zone === z.id);
  const live = rs.filter((x) => x.agent).length;
  r += `\n## ${z.name} — ${z.domain}\n\n*${z.charter}*\n\n**${rs.length} roles, ${live} live.** Branch: \`${z.branch}\`\n\n`;
  for (const role of rs) {
    r += `### ${role.name}\n\n`;
    r += `**${role.title}** · ${W.modelTiers[role.tier].label} tier · stationed at ${S[role.station].name}`;
    r += role.agent ? ` · **live as \`${role.agent}\`**\n\n` : `\n\n`;
    r += `${role.charter}\n\n`;
    r += `**Duties**\n\n${role.duties.map((d) => `- ${d}`).join('\n')}\n\n`;
    r += `| | |\n| --- | --- |\n`;
    r += `| Reads | ${role.reads.join(' · ')} |\n`;
    r += `| Writes | ${role.writes.join(' · ')} |\n`;
    r += `| Escalates to | ${R[role.escalatesTo] ? R[role.escalatesTo].name : role.escalatesTo} |\n\n`;
  }
}
writeFileSync(join(root, 'docs/03-ROSTER.md'), r);

/* ---------------- stations + tasks ---------------- */
let s = `# Stations and tasks\n\n${GEN}\n\n`;
s += `**${W.stations.length} stations, ${W.tasks.length} tasks.** A station is a place work happens; a task is a\n`;
s += `named piece of work that happens there. Every task states how you know it is done and the specific way it\n`;
s += `tends to go wrong — that second field is the one worth arguing about before anything gets built.\n\n`;
for (const z of W.zones) {
  const sts = W.stations.filter((x) => x.zone === z.id);
  s += `\n---\n\n## ${z.name} — ${z.domain}\n\n${z.charter}\n\n`;
  s += `**Owns:** ${z.owns.join(' · ')}\n\n`;
  s += `> **Where it breaks.** ${z.failsWhen}\n\n`;
  for (const st of sts) {
    const roles = W.roles.filter((x) => x.station === st.id);
    const tasks = W.tasks.filter((x) => x.station === st.id);
    const flows = W.flows.filter((f) => f.from === st.id || f.to === st.id);
    s += `### ${st.name}\n\n${st.purpose}\n\n`;
    s += `| | |\n| --- | --- |\n`;
    s += `| Takes in | ${st.inputs.join(' · ')} |\n`;
    s += `| Puts out | ${st.outputs.join(' · ')} |\n`;
    if (roles.length) s += `| Stationed here | ${roles.map((x) => x.name).join(' · ')} |\n`;
    s += `| Map position | ${st.x}, ${st.y} |\n\n`;
    if (tasks.length) {
      s += `#### Tasks\n\n`;
      for (const t of tasks) {
        s += `**${t.name}** — \`${t.id}\`, owned by ${R[t.owner].name}\n\n`;
        s += `| | |\n| --- | --- |\n`;
        s += `| Runs when | ${t.trigger} |\n| Takes | ${t.input} |\n| Produces | ${t.output} |\n`;
        s += `| Done when | ${t.doneWhen} |\n| **Watch for** | ${t.watchFor} |\n\n`;
      }
    }
    if (flows.length) {
      s += `#### Connections\n\n`;
      for (const f of flows) {
        const out = f.from === st.id;
        s += `- **${W.flowKinds[f.kind].label}** ${out ? '→' : '←'} ${S[out ? f.to : f.from].name} · *${f.label}*\n`;
      }
      s += `\n`;
    }
  }
}
writeFileSync(join(root, 'docs/04-STATIONS.md'), s);

/* ---------------- glossary ---------------- */
const TERMS = [
  ['The Steading', 'The whole agent ecosystem'],
  ['Zone', 'A bounded domain with its own crew, budget and failure modes'],
  ['Station', 'A place a specific kind of work happens — the unit a role is assigned to'],
  ['Role', 'An agent charter: purpose, duties, reads, writes, escalation'],
  ['Chore', 'A unit of work with an owner and a definition of done'],
  ['The Chore Board', 'The work ledger — the single authority on what is open'],
  ['Crew', 'The set of roles working one zone'],
  ['Row', 'One parallel worker inside a field'],
  ['Draw', 'A claim on shared model capacity or budget'],
  ['The Well', 'The shared capacity pool — rate limits and spend'],
  ['Dry well', 'Backpressure: the farm is at capacity and refuses new work'],
  ['Seed', 'A versioned prompt or charter an agent is grown from'],
  ['Shadow', 'Running a candidate on real traffic where nobody acts on its output'],
  ['Hardening off', 'Staged rollout by traffic percentage'],
  ['Gleaning', 'The recovery pass over everything a field dropped'],
  ['Composting', 'Turning a permanent failure into a reproducible eval case'],
  ['Winnowing', 'Distilling episodes into durable facts and discarding the rest'],
  ['Straying', 'A long-running agent working steadily on the wrong thing'],
  ['Ringing the bell', 'Paging a human'],
  ['The fence line', 'Blast radius — egress, filesystem reach and credential scope'],
  ['Weighing', 'Outbound inspection before anything leaves the farm'],
  ['Channel', 'A typed connection between stations: task, artifact, memory, signal or control']
];
let g = `# Glossary\n\n${GEN}\n\n`;
g += `The farm words are load-bearing: each one names a real thing in the system, and using the farm word in\n`;
g += `conversation is usually faster than the engineering one. The mapping below is the contract.\n\n`;
g += `## Farm terms\n\n| Term | Means |\n| --- | --- |\n`;
for (const [a, b] of TERMS) g += `| **${a}** | ${b} |\n`;
g += `\n## Zones at a glance\n\n| # | Zone | Domain | Stations | Roles | Branch |\n| --- | --- | --- | --- | --- | --- |\n`;
W.zones.forEach((z, i) => {
  g += `| ${i + 1} | **${z.name}** | ${z.domain} | ${W.stations.filter((x) => x.zone === z.id).length} | ${W.roles.filter((x) => x.zone === z.id).length} | \`${z.branch}\` |\n`;
});
g += `\n## Channel kinds\n\n| Channel | Carries |\n| --- | --- |\n`;
for (const [k, v] of Object.entries(W.flowKinds)) g += `| **${v.label}** | ${v.desc} |\n`;
writeFileSync(join(root, 'docs/07-GLOSSARY.md'), g);

console.log('generated docs/03-ROSTER.md, docs/04-STATIONS.md, docs/07-GLOSSARY.md');
