#!/usr/bin/env python3
"""Inline the generated QR into the sign master and render print-ready output.

Produces, in assets/print/:
  yard-sign.pdf         both faces, 18.25 x 24.25in (18x24 trim + .125in bleed) -- send this to the printer
  yard-sign-front.png   150 dpi proof for the README, email, and your own eyeballs
  yard-sign-back.png

Usage:
    pip install playwright segno
    python3 tools/make_qr.py          # only when the URL changes
    python3 tools/build_signs.py
"""

import os
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PRINT = ROOT / "assets" / "print"
MASTER = PRINT / "yard-sign.html"
QR = PRINT / "qr-yard-sign.svg"

PAGE_W_IN, PAGE_H_IN = 18.25, 24.25
PROOF_DPI = 72

# Some sandboxes ship a Chromium that does not match the pip-installed Playwright
# build number. If the bundled one is there, use it instead of failing.
_BUNDLED_CHROMIUM = pathlib.Path("/opt/pw-browsers/chromium")


def inline_qr() -> None:
    """Replace whatever sits between the QR markers with the current QR SVG."""
    svg = QR.read_text()
    svg = re.sub(r"<\?xml.*?\?>\s*", "", svg, flags=re.S).strip()
    html = MASTER.read_text()
    block = (
        "<!-- QR:START (generated by tools/make_qr.py — do not hand-edit) -->\n"
        f"      {svg}\n"
        "      <!-- QR:END -->"
    )
    html, n = re.subn(
        r"<!-- QR:START.*?QR:END -->", lambda _: block, html, flags=re.S
    )
    if n < 1:
        sys.exit("could not find the QR:START/QR:END markers in yard-sign.html")
    MASTER.write_text(html)
    print(f"inlined {QR.name} into {MASTER.name}")


def render() -> None:
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        launch_kwargs = {"args": ["--no-sandbox", "--font-render-hinting=none"]}
        if _BUNDLED_CHROMIUM.exists():
            launch_kwargs["executable_path"] = str(_BUNDLED_CHROMIUM)
        browser = p.chromium.launch(**launch_kwargs)
        page = browser.new_page(
            viewport={"width": int(PAGE_W_IN * 96), "height": int(PAGE_H_IN * 96)},
            device_scale_factor=PROOF_DPI / 96,
        )
        page.goto(MASTER.as_uri(), wait_until="networkidle")
        page.emulate_media(media="print")
        page.wait_for_timeout(600)  # let the webfonts settle before we snapshot

        page.pdf(
            path=str(PRINT / "yard-sign.pdf"),
            width=f"{PAGE_W_IN}in",
            height=f"{PAGE_H_IN}in",
            margin={"top": "0", "right": "0", "bottom": "0", "left": "0"},
            print_background=True,
            prefer_css_page_size=True,
        )
        print("wrote yard-sign.pdf")

        for name, selector in (("front", ".sheet.front"), ("back", ".sheet.back")):
            out = PRINT / f"yard-sign-{name}.png"
            page.locator(selector).screenshot(path=str(out))
            _squeeze(out)
            print(f"wrote {out.name} ({out.stat().st_size/1024:.0f} KB)")

        browser.close()


def _squeeze(path: pathlib.Path) -> None:
    """Re-encode the proof so a 2 MB screenshot does not land in the repo."""
    try:
        from PIL import Image
    except ImportError:
        return
    Image.open(path).convert("RGB").save(path, optimize=True)


if __name__ == "__main__":
    inline_qr()
    render()
