#!/usr/bin/env python3
"""Embed subsetted Fraunces + Inter into the sign master as base64 @font-face rules.

Print files have to be self-contained. A <link> to Google Fonts fails the moment
the machine doing the rendering is offline or behind a proxy, and it fails
silently -- you get Georgia on a $12 sign and only notice when 50 of them arrive.
This pulls the latin subsets, cuts them down to the characters the signs actually
use, and inlines them, so the master renders identically anywhere.

Both families are SIL Open Font License 1.1, which permits embedding.

Usage:
    pip install fonttools brotli
    python3 tools/embed_fonts.py     # needs network; only rerun if the type changes
"""

import base64
import io
import pathlib
import re
import subprocess
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
MASTER = ROOT / "assets" / "print" / "yard-sign.html"

UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120 Safari/537.36")
CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Fraunces:opsz,wght@144,600&family=Inter:wght@500;600;700&display=swap")

# every character that appears on either face, plus the ASCII we might type later
GLYPHS = "".join(chr(c) for c in range(0x20, 0x7F)) + "·—–’‘“”&"

START = "/* FONTS:START"
END = "/* FONTS:END */"


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read()


def latin_faces(css: str):
    """Yield (family, weight, url) for the latin (U+0000-00FF) subset of each face."""
    for block in re.findall(r"@font-face\s*\{(.*?)\}", css, re.S):
        if "U+0000-00FF" not in block:
            continue
        fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        wt = re.search(r"font-weight:\s*(\d+)", block).group(1)
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)
        yield fam, wt, url


def subset(raw: bytes, weight: str) -> bytes:
    from fontTools.ttLib import TTFont
    from fontTools.subset import Subsetter, Options
    from fontTools.varLib.instancer import instantiateVariableFont

    font = TTFont(io.BytesIO(raw))
    if "fvar" in font:
        # Pin every axis so we ship one static cut per weight instead of the
        # whole design space. Fraunces alone carries opsz, SOFT and WONK.
        axes = {a.axisTag: a.defaultValue for a in font["fvar"].axes}
        if "wght" in axes:
            axes["wght"] = float(weight)
        if "opsz" in axes:
            axes["opsz"] = font["fvar"].axes[
                [a.axisTag for a in font["fvar"].axes].index("opsz")].maxValue
        font = instantiateVariableFont(font, axes, updateFontNames=False)
    opts = Options()
    opts.layout_features = ["kern", "liga", "calt", "tnum", "onum", "lnum"]
    opts.notdef_outline = True
    opts.desubroutinize = True
    ss = Subsetter(options=opts)
    ss.populate(text=GLYPHS)
    ss.subset(font)
    font.flavor = "woff2"
    out = io.BytesIO()
    font.save(out)
    return out.getvalue()


def main() -> None:
    try:
        import fontTools  # noqa: F401
        import brotli  # noqa: F401
    except ImportError:
        sys.exit("run: pip install fonttools brotli")

    css = get(CSS_URL).decode()
    rules = []
    total = 0
    for fam, wt, url in latin_faces(css):
        data = subset(get(url), wt)
        total += len(data)
        b64 = base64.b64encode(data).decode()
        rules.append(
            f"  @font-face{{font-family:'{fam}';font-style:normal;font-weight:{wt};"
            f"font-display:block;src:url(data:font/woff2;base64,{b64}) format('woff2')}}"
        )
        print(f"  {fam} {wt}: {len(data)/1024:.1f} KB")

    body = (
        f"{START} — generated by tools/embed_fonts.py; do not hand-edit.\n"
        "     Fraunces and Inter, SIL OFL 1.1, subset to the characters these signs use. */\n"
        + "\n".join(rules)
        + f"\n  {END}"
    )
    html = MASTER.read_text()
    html, n = re.subn(re.escape(START) + r".*?" + re.escape(END), lambda _: body, html, flags=re.S)
    if n != 1:
        sys.exit("could not find the FONTS:START/FONTS:END markers in yard-sign.html")
    MASTER.write_text(html)
    print(f"embedded {total/1024:.1f} KB of type into {MASTER.name}")


if __name__ == "__main__":
    main()
